version: '3'
services:
  backend:
    build: .
    ports:
      - 8080:8080
  frontend:
    build: ./react-frontend
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
    restart: always
